# Generated by Django 4.0.3 on 2022-07-23 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '__first__'),
        ('opdrx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opdrxmodel',
            name='opdrx_UHID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+++', to='homepage.homepagemodel'),
        ),
    ]
